// execuetion loads .github/workflows/*.cue and generates the
// corresponding .yml files. The CUE module and its dependencies are embedded
// in the binary, so consuming repos need no cue.mod directory, no network
// access, and no CUE toolchain.
package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/load"
	cueyaml "cuelang.org/go/encoding/yaml"
	docs "github.com/urfave/cli-docs/v3"
	"github.com/urfave/cli/v3"
	"sigs.k8s.io/yaml/kyaml"

	"github.com/sondr3/actions/internal/cuemod"
)

const (
	workflowDir = ".github/workflows"

	// generatedMarker is the first line of every generated file; its presence
	// is what distinguishes generated workflows from hand-written ones.
	generatedMarker = "# Code generated by execuetion; DO NOT EDIT."
)

// Exit codes: 0 ok, 1 stale/orphan (check mode), 2 evaluation error.
const (
	exitStale = 1
	exitEval  = 2
)

// A Workflow is one generated workflow: the .cue source it came from, the
// .yml path it maps to, and the generated content.
type Workflow struct {
	Source string
	Output string
	Data   []byte
}

// findRepoRoot walks up from start to the nearest directory containing .git.
func findRepoRoot(start string) (string, error) {
	dir, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no git repository found in or above %s (use --repo-root)", start)
		}
		dir = parent
	}
}

// buildOverlay maps every embedded .cue file onto its phantom location under
// repoRoot. Overlaid files shadow on-disk files at the same path, so a real
// cue.mod in the consuming repo is rejected before this is used.
func buildOverlay(repoRoot string) (map[string]load.Source, error) {
	overlay := make(map[string]load.Source)
	err := fs.WalkDir(cuemod.FS, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		if filepath.Ext(path) != ".cue" {
			return nil
		}
		data, err := cuemod.FS.ReadFile(path)
		if err != nil {
			return err
		}
		overlay[filepath.Join(repoRoot, filepath.FromSlash(path))] = load.FromBytes(data)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return overlay, nil
}

// encode renders a fully evaluated workflow in the requested format: KYAML
// (the default, a JSON-ish YAML subset GitHub parses like any other YAML) or
// regular block-style YAML.
func encode(v cue.Value, format string) ([]byte, error) {
	switch format {
	case "yaml":
		return cueyaml.Encode(v)
	case "kyaml":
		encoder := kyaml.Encoder{Compact: false}
		data, err := encoder.Marshal(v)
		if err != nil {
			return nil, err
		}
		data = bytes.ReplaceAll(data, []byte("\t"), []byte("  "))
		if !bytes.HasSuffix(data, []byte("\n")) {
			data = append(data, '\n')
		}
		return data, nil
	default:
		return nil, fmt.Errorf("invalid format: %s, must be either 'kyaml' or 'yaml'", format)
	}
}

// outputName maps a workflow source filename to its output filename
// (ci.cue -> ci.yml). The filename is the stable key; the workflow name:
// field can be renamed freely.
func outputName(cueFile string) string {
	return strings.TrimSuffix(filepath.Base(cueFile), ".cue") + ".yml"
}

// generate evaluates every .github/workflows/*.cue file in repoRoot. Each
// file is loaded as its own instance so workflows do not unify with each
// other. Evaluation errors are collected across all files before returning.
func generate(repoRoot, format string) ([]Workflow, error) {
	repoRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return nil, err
	}
	if _, err := os.Stat(filepath.Join(repoRoot, "cue.mod")); err == nil {
		return nil, fmt.Errorf("%s/cue.mod exists on disk; execuetion brings its own CUE module and cannot run in a repo with one", repoRoot)
	}

	sources, err := filepath.Glob(filepath.Join(repoRoot, workflowDir, "*.cue"))
	if err != nil {
		return nil, err
	}
	if len(sources) == 0 {
		return nil, fmt.Errorf("no .cue files found in %s", filepath.Join(repoRoot, workflowDir))
	}

	overlay, err := buildOverlay(repoRoot)
	if err != nil {
		return nil, err
	}

	ctx := cuecontext.New()
	var workflows []Workflow
	var errs []error
	for _, src := range sources {
		cfg := &load.Config{
			Dir:        repoRoot,
			ModuleRoot: repoRoot,
			Overlay:    overlay,
		}
		rel, err := filepath.Rel(repoRoot, src)
		if err != nil {
			return nil, err
		}
		insts := load.Instances([]string{"./" + filepath.ToSlash(rel)}, cfg)
		if len(insts) != 1 {
			errs = append(errs, fmt.Errorf("%s: expected 1 instance, got %d", rel, len(insts)))
			continue
		}
		if insts[0].Err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", rel, insts[0].Err))
			continue
		}
		v := ctx.BuildInstance(insts[0])
		if v.Err() != nil {
			errs = append(errs, fmt.Errorf("%s: %w", rel, v.Err()))
			continue
		}
		if err := v.Validate(cue.Concrete(true), cue.Final()); err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", rel, err))
			continue
		}
		data, err := encode(v, format)
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", rel, err))
			continue
		}
		workflows = append(workflows, Workflow{
			Source: src,
			Output: filepath.Join(filepath.Dir(src), outputName(src)),
			Data:   append([]byte(generatedMarker+"\n"), data...),
		})
	}
	if len(errs) > 0 {
		return nil, errors.Join(errs...)
	}
	return workflows, nil
}

// writeWorkflows writes each generated workflow next to its source.
func writeWorkflows(workflows []Workflow) error {
	var written, unchanged int
	for _, wf := range workflows {
		if existing, err := os.ReadFile(wf.Output); err == nil && bytes.Equal(existing, wf.Data) {
			unchanged++
			continue
		}
		if err := os.WriteFile(wf.Output, wf.Data, 0o644); err != nil {
			return err
		}
		written++
	}
	fmt.Printf("Wrote %d workflow(s), %d up to date\n", written, unchanged)
	return nil
}

// normalize makes byte comparison robust against Windows autocrlf checkouts:
// CRLF becomes LF and trailing whitespace is stripped from every line.
func normalize(b []byte) []byte {
	b = bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
	lines := strings.Split(string(b), "\n")
	for i, line := range lines {
		lines[i] = strings.TrimRight(line, " \t")
	}
	return []byte(strings.Join(lines, "\n"))
}

// isGenerated reports whether a committed file carries the generated marker.
func isGenerated(b []byte) bool {
	return bytes.HasPrefix(normalize(b), []byte(generatedMarker))
}

// check compares the generated workflows against the committed files and
// scans for orphans: committed workflow files that no .cue source produces.
// A generated orphan means a source was deleted without its output; unless
// allowHandwritten is set, any other workflow file fails too, since header
// presence is only a reliable orphan signal when all workflows go through
// CUE. Returns a list of problems; empty means everything is up to date.
func check(repoRoot string, workflows []Workflow, allowHandwritten bool) ([]string, error) {
	display := func(path string) string {
		if rel, err := filepath.Rel(repoRoot, path); err == nil {
			return filepath.ToSlash(rel)
		}
		return path
	}

	var problems []string
	expected := make(map[string]bool, len(workflows))
	for _, wf := range workflows {
		expected[wf.Output] = true
		existing, err := os.ReadFile(wf.Output)
		switch {
		case errors.Is(err, fs.ErrNotExist):
			problems = append(problems, fmt.Sprintf("%s: missing", display(wf.Output)))
		case err != nil:
			return nil, err
		case !bytes.Equal(normalize(existing), normalize(wf.Data)):
			problems = append(problems, fmt.Sprintf("%s: out of date", display(wf.Output)))
		}
	}

	for _, pattern := range []string{"*.yml", "*.yaml"} {
		matches, err := filepath.Glob(filepath.Join(repoRoot, workflowDir, pattern))
		if err != nil {
			return nil, err
		}
		for _, path := range matches {
			if expected[path] {
				continue
			}
			existing, err := os.ReadFile(path)
			if err != nil {
				return nil, err
			}
			switch {
			case isGenerated(existing):
				problems = append(problems, fmt.Sprintf("%s: generated file has no matching .cue source", display(path)))
			case !allowHandwritten:
				problems = append(problems, fmt.Sprintf("%s: hand-written workflow; all workflows must be generated from CUE (or pass --allow-handwritten)", display(path)))
			}
		}
	}
	return problems, nil
}

func run(repoRoot, format string, checkMode, allowHandwritten bool) error {
	if repoRoot == "" {
		root, err := findRepoRoot(".")
		if err != nil {
			return cli.Exit(err.Error(), exitEval)
		}
		repoRoot = root
	}
	repoRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return cli.Exit(err.Error(), exitEval)
	}

	workflows, err := generate(repoRoot, format)
	if err != nil {
		return cli.Exit(err.Error(), exitEval)
	}

	if checkMode {
		problems, err := check(repoRoot, workflows, allowHandwritten)
		if err != nil {
			return cli.Exit(err.Error(), exitEval)
		}
		if len(problems) > 0 {
			msg := fmt.Sprintf("%d workflow(s) not up to date, rerun execuetion to fix:\n%s",
				len(problems), strings.Join(problems, "\n"))
			return cli.Exit(msg, exitStale)
		}
		return nil
	}

	if err := writeWorkflows(workflows); err != nil {
		return cli.Exit(err.Error(), exitEval)
	}
	return nil
}

func main() {
	var repoRoot string
	var format string
	var checkMode bool
	var allowHandwritten bool

	app := &cli.Command{
		Name:                  "execuetion",
		Usage:                 "Generate GitHub Actions workflows from CUE",
		Description:           "execuetion evaluates .github/workflows/*.cue against the embedded CUE module and writes the corresponding .yml files next to the sources",
		Version:               "0.1.0",
		EnableShellCompletion: true,
		Suggest:               true,

		Commands: []*cli.Command{
			{
				Name:   "man",
				Hidden: true,
				Action: func(ctx context.Context, cmd *cli.Command) error {
					man, err := docs.ToMan(cmd.Root())
					if err != nil {
						return err
					}
					fmt.Println(man)
					return nil
				},
			},
			{
				Name:   "markdown",
				Hidden: true,
				Action: func(ctx context.Context, cmd *cli.Command) error {
					man, err := docs.ToMarkdown(cmd.Root())
					if err != nil {
						return err
					}
					fmt.Println(man)
					return nil
				},
			},
		},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:        "repo-root",
				Aliases:     []string{"r"},
				Usage:       "Repository root to operate on",
				DefaultText: "nearest git root above the working directory",
				Destination: &repoRoot,
			},
			&cli.StringFlag{
				Name:        "format",
				Aliases:     []string{"f"},
				Usage:       "Output format (kyaml|yaml)",
				Value:       "kyaml",
				DefaultText: "kyaml",
				Destination: &format,
				Validator: func(s string) error {
					if s != "kyaml" && s != "yaml" {
						return fmt.Errorf("invalid format: %s, must be either 'kyaml' or 'yaml'", s)
					}
					return nil
				},
			},
			&cli.BoolFlag{
				Name:        "check",
				Aliases:     []string{"c"},
				Usage:       "Verify that the committed workflows are up to date without writing",
				Destination: &checkMode,
			},
			&cli.BoolFlag{
				Name:        "allow-handwritten",
				Usage:       "Permit workflow files without the generated-code header during --check",
				Destination: &allowHandwritten,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			return run(repoRoot, format, checkMode, allowHandwritten)
		},
	}

	if err := app.Run(context.Background(), os.Args); err != nil {
		if exitErr, ok := err.(cli.ExitCoder); ok {
			fmt.Fprintln(os.Stderr, exitErr.Error())
			os.Exit(exitErr.ExitCode())
		}
		log.Fatal(err)
	}
}
