// execuetion loads .github/workflows/*.cue and generates the
// corresponding .yml files. The CUE module and its dependencies are embedded
// in the binary, so consuming repos need no cue.mod directory, no network
// access, and no CUE toolchain.
package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/tabwriter"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/load"
	cueyaml "cuelang.org/go/encoding/yaml"
	"cuelang.org/go/mod/modfile"
	docs "github.com/urfave/cli-docs/v3"
	"github.com/urfave/cli/v3"
	"sigs.k8s.io/yaml/kyaml"

	"github.com/sondr3/execuetion/internal/cuemod"
	"github.com/sondr3/execuetion/internal/pin"
)

const (
	workflowDir = ".github/workflows"

	// generatedMarker is the first line of every generated file; its presence
	// is what distinguishes generated workflows from hand-written ones.
	generatedMarker = "# Code generated by execuetion; DO NOT EDIT."
)

// Exit codes: 0 ok, 1 stale/orphan (check mode), 2 evaluation error.
const (
	exitStale = 1
	exitEval  = 2
)

// A Workflow is one generated workflow: the .cue source it came from, the
// .yml path it maps to, and the generated content.
type Workflow struct {
	Source string
	Output string
	Data   []byte
}

// findRepoRoot walks up from start to the nearest directory containing .git.
func findRepoRoot(start string) (string, error) {
	dir, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no git repository found in or above %s (use --repo-root)", start)
		}
		dir = parent
	}
}

// buildOverlay maps every embedded .cue file onto its phantom location under
// the workflows directory, which acts as the CUE module root — the repo root
// stays untouched. Overlaid files shadow on-disk files at the same path,
// which is what keeps generation hermetic when an editor-facing cue.mod
// (see validateOnDiskCueMod) is present.
func buildOverlay(wfDir string) (map[string]load.Source, error) {
	overlay := make(map[string]load.Source)
	err := fs.WalkDir(cuemod.FS, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		if filepath.Ext(path) != ".cue" {
			return nil
		}
		data, err := cuemod.FS.ReadFile(path)
		if err != nil {
			return err
		}
		overlay[filepath.Join(wfDir, filepath.FromSlash(path))] = load.FromBytes(data)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return overlay, nil
}

// encode renders a fully evaluated workflow in the requested format: KYAML
// (the default, a JSON-ish YAML subset GitHub parses like any other YAML) or
// regular block-style YAML.
func encode(v cue.Value, format string) ([]byte, error) {
	switch format {
	case "yaml":
		return cueyaml.Encode(v)
	case "kyaml":
		encoder := kyaml.Encoder{Compact: false}
		data, err := encoder.Marshal(v)
		if err != nil {
			return nil, err
		}
		data = bytes.ReplaceAll(data, []byte("\t"), []byte("  "))
		if !bytes.HasSuffix(data, []byte("\n")) {
			data = append(data, '\n')
		}
		return data, nil
	default:
		return nil, fmt.Errorf("invalid format: %s, must be either 'kyaml' or 'yaml'", format)
	}
}

// outputName maps a workflow source filename to its output filename
// (ci.cue -> ci.yml). The filename is the stable key; the workflow name:
// field can be renamed freely.
func outputName(cueFile string) string {
	return strings.TrimSuffix(filepath.Base(cueFile), ".cue") + ".yml"
}

// embeddedModule parses the embedded phantom module.cue.
func embeddedModule() (*modfile.File, error) {
	data, err := cuemod.FS.ReadFile("cue.mod/module.cue")
	if err != nil {
		return nil, err
	}
	return modfile.Parse(data, "cue.mod/module.cue")
}

// validateOnDiskCueMod permits a real cue.mod in the workflows directory as
// long as it cannot interfere with generation. Such a cue.mod exists purely
// for editors: the CUE language server needs an on-disk module.cue to
// resolve imports and autocomplete, while generation shadows it with the
// embedded one (overlaid files win at the same path) and stays hermetic.
// The legacy content directories are rejected because the loader would merge
// them with the embedded vendored tree.
func validateOnDiskCueMod(wfDir string) error {
	cueModDir := filepath.Join(wfDir, "cue.mod")
	if _, err := os.Stat(cueModDir); errors.Is(err, fs.ErrNotExist) {
		return nil
	} else if err != nil {
		return err
	}

	for _, dir := range []string{"pkg", "gen", "usr"} {
		if _, err := os.Stat(filepath.Join(cueModDir, dir)); err == nil {
			return fmt.Errorf("%s exists and would merge with the module embedded in execuetion; an on-disk cue.mod may only contain module.cue (editor support, see 'execuetion --init')", filepath.Join(cueModDir, dir))
		}
	}

	data, err := os.ReadFile(filepath.Join(cueModDir, "module.cue"))
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	} else if err != nil {
		return err
	}
	onDisk, err := modfile.ParseNonStrict(data, "cue.mod/module.cue")
	if err != nil {
		return fmt.Errorf("invalid %s: %w", filepath.Join(cueModDir, "module.cue"), err)
	}
	embedded, err := embeddedModule()
	if err != nil {
		return err
	}
	if onDisk.ModuleRootPath() != embedded.ModuleRootPath() {
		fmt.Fprintf(os.Stderr, "warning: %s declares module %q, but generation uses %q; editor import resolution will disagree with execuetion (rerun 'execuetion --init' to fix)\n",
			filepath.Join(cueModDir, "module.cue"), onDisk.ModuleRootPath(), embedded.ModuleRootPath())
	}
	return nil
}

// initCueMod writes an editor-facing cue.mod/module.cue into the workflows
// directory: the embedded module definition plus a registry dependency on
// the vendored githubactions version, so that cue lsp and editor extensions
// can resolve imports and autocomplete. Generation never reads it.
func initCueMod(repoRoot string) error {
	repoRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return err
	}
	wfDir := filepath.Join(repoRoot, workflowDir)

	mf, err := embeddedModule()
	if err != nil {
		return err
	}
	mf.Deps = map[string]*modfile.Dep{
		"cue.dev/x/githubactions@v0": {
			Version: cuemod.GithubActionsVersion,
			Default: true,
		},
	}
	data, err := modfile.Format(mf)
	if err != nil {
		return err
	}

	path := filepath.Join(wfDir, "cue.mod", "module.cue")
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, data) {
		fmt.Printf("%s is up to date\n", path)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return err
	}
	fmt.Printf("Wrote %s\n", path)
	return nil
}

// generate evaluates every .github/workflows/*.cue file in repoRoot. Each
// file is loaded as its own instance so workflows do not unify with each
// other. Evaluation errors are collected across all files before returning.
func generate(repoRoot, format string) ([]Workflow, error) {
	repoRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return nil, err
	}
	wfDir := filepath.Join(repoRoot, workflowDir)
	if err := validateOnDiskCueMod(wfDir); err != nil {
		return nil, err
	}

	sources, err := filepath.Glob(filepath.Join(wfDir, "*.cue"))
	if err != nil {
		return nil, err
	}
	if len(sources) == 0 {
		return nil, fmt.Errorf("no .cue files found in %s", wfDir)
	}

	overlay, err := buildOverlay(wfDir)
	if err != nil {
		return nil, err
	}

	ctx := cuecontext.New()
	var workflows []Workflow
	var errs []error
	for _, src := range sources {
		cfg := &load.Config{
			Dir:        wfDir,
			ModuleRoot: wfDir,
			Overlay:    overlay,
		}
		rel, err := filepath.Rel(repoRoot, src)
		if err != nil {
			return nil, err
		}
		insts := load.Instances([]string{"./" + filepath.Base(src)}, cfg)
		if len(insts) != 1 {
			errs = append(errs, fmt.Errorf("%s: expected 1 instance, got %d", rel, len(insts)))
			continue
		}
		if insts[0].Err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", rel, insts[0].Err))
			continue
		}
		v := ctx.BuildInstance(insts[0])
		if v.Err() != nil {
			errs = append(errs, fmt.Errorf("%s: %w", rel, v.Err()))
			continue
		}
		if err := v.Validate(cue.Concrete(true), cue.Final()); err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", rel, err))
			continue
		}
		data, err := encode(v, format)
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: %w", rel, err))
			continue
		}
		workflows = append(workflows, Workflow{
			Source: src,
			Output: filepath.Join(filepath.Dir(src), outputName(src)),
			Data:   append([]byte(generatedMarker+"\n"), data...),
		})
	}
	if len(errs) > 0 {
		return nil, errors.Join(errs...)
	}
	return workflows, nil
}

// writeWorkflows writes each generated workflow next to its source.
func writeWorkflows(workflows []Workflow) error {
	var written, unchanged int
	for _, wf := range workflows {
		if existing, err := os.ReadFile(wf.Output); err == nil && bytes.Equal(existing, wf.Data) {
			unchanged++
			continue
		}
		if err := os.WriteFile(wf.Output, wf.Data, 0o644); err != nil {
			return err
		}
		written++
	}
	fmt.Printf("Wrote %d workflow(s), %d up to date\n", written, unchanged)
	return nil
}

// normalize makes byte comparison robust against Windows autocrlf checkouts:
// CRLF becomes LF and trailing whitespace is stripped from every line.
func normalize(b []byte) []byte {
	b = bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
	lines := strings.Split(string(b), "\n")
	for i, line := range lines {
		lines[i] = strings.TrimRight(line, " \t")
	}
	return []byte(strings.Join(lines, "\n"))
}

// firstDiff points at the first line where the committed content diverges
// from the generated content, so a --check failure in CI logs is
// self-explanatory.
func firstDiff(have, want []byte) string {
	haveLines := strings.Split(string(have), "\n")
	wantLines := strings.Split(string(want), "\n")
	for i := 0; i < len(haveLines) || i < len(wantLines); i++ {
		var h, w string
		if i < len(haveLines) {
			h = haveLines[i]
		}
		if i < len(wantLines) {
			w = wantLines[i]
		}
		if h != w {
			return fmt.Sprintf("first difference at line %d: have %q, want %q",
				i+1, strings.TrimSpace(h), strings.TrimSpace(w))
		}
	}
	return "contents differ"
}

// isGenerated reports whether a committed file carries the generated marker.
func isGenerated(b []byte) bool {
	return bytes.HasPrefix(normalize(b), []byte(generatedMarker))
}

// check compares the generated workflows against the committed files and
// scans for orphans: committed workflow files that no .cue source produces.
// A generated orphan means a source was deleted without its output; unless
// allowHandwritten is set, any other workflow file fails too, since header
// presence is only a reliable orphan signal when all workflows go through
// CUE. Returns a list of problems; empty means everything is up to date.
func check(repoRoot string, workflows []Workflow, allowHandwritten bool) ([]string, error) {
	display := func(path string) string {
		if rel, err := filepath.Rel(repoRoot, path); err == nil {
			return filepath.ToSlash(rel)
		}
		return path
	}

	var problems []string
	expected := make(map[string]bool, len(workflows))
	for _, wf := range workflows {
		expected[wf.Output] = true
		existing, err := os.ReadFile(wf.Output)
		switch {
		case errors.Is(err, fs.ErrNotExist):
			problems = append(problems, fmt.Sprintf("%s: missing", display(wf.Output)))
		case err != nil:
			return nil, err
		case !bytes.Equal(normalize(existing), normalize(wf.Data)):
			problems = append(problems, fmt.Sprintf("%s: out of date (%s)",
				display(wf.Output), firstDiff(normalize(existing), normalize(wf.Data))))
		}
	}

	for _, pattern := range []string{"*.yml", "*.yaml"} {
		matches, err := filepath.Glob(filepath.Join(repoRoot, workflowDir, pattern))
		if err != nil {
			return nil, err
		}
		for _, path := range matches {
			if expected[path] {
				continue
			}
			existing, err := os.ReadFile(path)
			if err != nil {
				return nil, err
			}
			switch {
			case isGenerated(existing):
				problems = append(problems, fmt.Sprintf("%s: generated file has no matching .cue source", display(path)))
			case !allowHandwritten:
				problems = append(problems, fmt.Sprintf("%s: hand-written workflow; all workflows must be generated from CUE (or pass --allow-handwritten)", display(path)))
			}
		}
	}
	return problems, nil
}

// newPinner builds the pinner every pinning-related path shares: the
// global cache plus the GitHub API.
func newPinner(updatePins bool) (*pin.Pinner, error) {
	cachePath, err := pin.DefaultPath()
	if err != nil {
		return nil, err
	}
	return &pin.Pinner{
		Resolver: pin.NewGitHub(),
		Cache:    pin.Open(cachePath),
		Update:   updatePins,
	}, nil
}

// shortSHA abbreviates a commit SHA for display.
func shortSHA(sha string) string {
	if len(sha) > 8 {
		return sha[:8]
	}
	return sha
}

// pinWorkflows rewrites action refs in every generated workflow to commit
// SHAs and reports any pins that moved during an --update-pins run.
func pinWorkflows(ctx context.Context, pinner *pin.Pinner, workflows []Workflow) error {
	docs := make([][]byte, len(workflows))
	for i := range workflows {
		docs[i] = workflows[i].Data
	}
	pinned, err := pinner.Pin(ctx, docs)
	if err != nil {
		return err
	}
	for i := range workflows {
		workflows[i].Data = pinned[i]
	}
	for _, ch := range pinner.Changes {
		versions := ""
		if ch.OldVersion != "" || ch.NewVersion != "" {
			versions = fmt.Sprintf(" (%s → %s)", ch.OldVersion, ch.NewVersion)
		}
		fmt.Printf("updated %s: %s → %s%s\n", ch.Key, shortSHA(ch.OldSHA), shortSHA(ch.NewSHA), versions)
	}
	return nil
}

// verifyPins audits every committed workflow file in the repo: each
// SHA-pinned uses: line with a version comment is checked against what
// that version actually resolves to, catching tampered pins and lying
// comments — in hand-written workflows too. With a warm cache this is
// offline; resolutions it performs are cached like any other.
func verifyPins(ctx context.Context, pinner *pin.Pinner, repoRoot string) ([]string, error) {
	type site struct {
		file string
		sha  string
	}
	sites := make(map[string][]site)
	refs := make(map[string]pin.Ref)
	for _, pattern := range []string{"*.yml", "*.yaml"} {
		matches, err := filepath.Glob(filepath.Join(repoRoot, workflowDir, pattern))
		if err != nil {
			return nil, err
		}
		for _, path := range matches {
			data, err := os.ReadFile(path)
			if err != nil {
				return nil, err
			}
			display := path
			if rel, err := filepath.Rel(repoRoot, path); err == nil {
				display = filepath.ToSlash(rel)
			}
			for _, pr := range pin.PinnedRefs(data) {
				key := pr.Ref.Key()
				sites[key] = append(sites[key], site{file: display, sha: pr.SHA})
				refs[key] = pr.Ref
			}
		}
	}

	keys := make([]string, 0, len(refs))
	for key := range refs {
		keys = append(keys, key)
	}
	slices.Sort(keys)

	var problems []string
	for _, key := range keys {
		res, err := pinner.Resolve(ctx, refs[key])
		if err != nil {
			return nil, fmt.Errorf("verifying %s: %w", key, err)
		}
		for _, s := range sites[key] {
			if !strings.EqualFold(s.sha, res.SHA) {
				problems = append(problems, fmt.Sprintf("%s: pinned to %s, but %s resolves to %s",
					s.file, shortSHA(s.sha), key, shortSHA(res.SHA)))
			}
		}
	}
	if err := pinner.Cache.Save(); err != nil {
		return nil, err
	}
	return problems, nil
}

// dumpPins prints the global pin cache.
func dumpPins() error {
	cachePath, err := pin.DefaultPath()
	if err != nil {
		return err
	}
	entries := pin.Open(cachePath).All()
	if len(entries) == 0 {
		fmt.Printf("pin cache %s is empty\n", cachePath)
		return nil
	}
	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	fmt.Fprintln(w, "REF\tSHA\tVERSION\tRESOLVED")
	for _, e := range entries {
		version := e.Version
		if version == "" {
			version = "-"
		}
		fmt.Fprintf(w, "%s\t%s\t%s\t%s\n", e.Key, e.SHA, version, e.ResolvedAt.Format("2006-01-02"))
	}
	return w.Flush()
}

func run(ctx context.Context, repoRoot, format string, checkMode, allowHandwritten, noPin, updatePins bool) error {
	var pinner *pin.Pinner
	if !noPin {
		p, err := newPinner(updatePins)
		if err != nil {
			return cli.Exit(err.Error(), exitEval)
		}
		pinner = p
	}

	if repoRoot == "" {
		root, err := findRepoRoot(".")
		if err != nil {
			return cli.Exit(err.Error(), exitEval)
		}
		repoRoot = root
	}
	repoRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return cli.Exit(err.Error(), exitEval)
	}

	workflows, err := generate(repoRoot, format)
	if err != nil {
		return cli.Exit(err.Error(), exitEval)
	}

	if pinner != nil {
		if err := pinWorkflows(ctx, pinner, workflows); err != nil {
			return cli.Exit(err.Error(), exitEval)
		}
	}

	if checkMode {
		problems, err := check(repoRoot, workflows, allowHandwritten)
		if err != nil {
			return cli.Exit(err.Error(), exitEval)
		}
		if pinner != nil {
			verifyProblems, err := verifyPins(ctx, pinner, repoRoot)
			if err != nil {
				return cli.Exit(err.Error(), exitEval)
			}
			problems = append(problems, verifyProblems...)
		}
		if len(problems) > 0 {
			msg := fmt.Sprintf("%d workflow(s) not up to date, rerun execuetion to fix:\n%s",
				len(problems), strings.Join(problems, "\n"))
			return cli.Exit(msg, exitStale)
		}
		return nil
	}

	if err := writeWorkflows(workflows); err != nil {
		return cli.Exit(err.Error(), exitEval)
	}
	return nil
}

func main() {
	var repoRoot string
	var format string
	var checkMode bool
	var allowHandwritten bool
	var noPin bool
	var updatePins bool
	var dump bool
	var initMode bool
	var manPage bool
	var markdown bool

	app := &cli.Command{
		Name:                  "execuetion",
		Usage:                 "Generate GitHub Actions workflows from CUE",
		Description:           "execuetion evaluates .github/workflows/*.cue against the embedded CUE module and writes the corresponding .yml files next to the sources",
		Version:               "0.1.0",
		EnableShellCompletion: true,
		HideHelpCommand:       true,
		Suggest:               true,

		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:        "repo-root",
				Aliases:     []string{"r"},
				Usage:       "Repository root to operate on",
				DefaultText: "nearest git root above the working directory",
				Destination: &repoRoot,
			},
			&cli.StringFlag{
				Name:        "format",
				Aliases:     []string{"f"},
				Usage:       "Output format (kyaml|yaml)",
				Value:       "kyaml",
				DefaultText: "kyaml",
				Destination: &format,
				Validator: func(s string) error {
					if s != "kyaml" && s != "yaml" {
						return fmt.Errorf("invalid format: %s, must be either 'kyaml' or 'yaml'", s)
					}
					return nil
				},
			},
			&cli.BoolFlag{
				Name:        "check",
				Aliases:     []string{"c"},
				Usage:       "Verify that the committed workflows are up to date without writing",
				Destination: &checkMode,
			},
			&cli.BoolFlag{
				Name:        "allow-handwritten",
				Usage:       "Permit workflow files without the generated-code header during --check",
				Destination: &allowHandwritten,
			},
			&cli.BoolFlag{
				Name:        "no-pin",
				Usage:       "Skip pinning action refs to commit SHAs",
				Destination: &noPin,
			},
			&cli.BoolFlag{
				Name:        "update-pins",
				Usage:       "Re-resolve every action ref, refreshing the pin cache",
				Destination: &updatePins,
			},
			&cli.BoolFlag{
				Name:        "dump",
				Usage:       "Print the global pin cache and exit",
				Destination: &dump,
			},
			&cli.BoolFlag{
				Name:        "init",
				Usage:       "Write an editor-facing cue.mod/module.cue so cue lsp can resolve imports; generation never reads it",
				Destination: &initMode,
			},
			&cli.BoolFlag{
				Name:        "man",
				Hidden:      true,
				Destination: &manPage,
			},
			&cli.BoolFlag{
				Name:        "markdown",
				Hidden:      true,
				Destination: &markdown,
			},
		},
		Action: func(ctx context.Context, cmd *cli.Command) error {
			// There are no subcommands; a positional argument is a mistake
			// (likely a pre-flag invocation like "execuetion init").
			if cmd.Args().Len() > 0 {
				return cli.Exit(fmt.Sprintf("unexpected argument %q (did you mean --%s?)", cmd.Args().First(), cmd.Args().First()), exitEval)
			}
			switch {
			case manPage, markdown:
				render := docs.ToMan
				if markdown {
					render = docs.ToMarkdown
				}
				page, err := render(cmd.Root())
				if err != nil {
					return err
				}
				fmt.Println(page)
				return nil
			case dump:
				if err := dumpPins(); err != nil {
					return cli.Exit(err.Error(), exitEval)
				}
				return nil
			case initMode:
				if repoRoot == "" {
					root, err := findRepoRoot(".")
					if err != nil {
						return cli.Exit(err.Error(), exitEval)
					}
					repoRoot = root
				}
				if err := initCueMod(repoRoot); err != nil {
					return cli.Exit(err.Error(), exitEval)
				}
				return nil
			default:
				return run(ctx, repoRoot, format, checkMode, allowHandwritten, noPin, updatePins)
			}
		},
	}

	if err := app.Run(context.Background(), os.Args); err != nil {
		if exitErr, ok := err.(cli.ExitCoder); ok {
			fmt.Fprintln(os.Stderr, exitErr.Error())
			os.Exit(exitErr.ExitCode())
		}
		log.Fatal(err)
	}
}
