package pin

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"testing"
)

const (
	checkoutSHA = "08c6903cd8c0fde910a37f88322edcfb5dd907a8"
	setupGoSHA  = "d35c59abb061a4a6e9a5ee8ecf3f7a3d147d2c9c"
)

func TestParseUsesLine(t *testing.T) {
	tests := []struct {
		name string
		line string
		ok   bool
		key  string
	}{
		{"kyaml quoted with comma", `        uses: "actions/checkout@v7",`, true, "actions/checkout@v7"},
		{"yaml dash plain", `      - uses: actions/setup-go@v6`, true, "actions/setup-go@v6"},
		{"single quoted", `  - uses: 'actions/cache@v4'`, true, "actions/cache@v4"},
		{"unquoted kyaml", `        uses: actions/checkout@v7,`, true, "actions/checkout@v7"},
		{"reusable workflow", `    uses: octo/repo/.github/workflows/ci.yml@v1`, true, "octo/repo@v1"},
		{"branch ref", `      - uses: actions/checkout@main`, true, "actions/checkout@main"},
		{"already pinned sha", fmt.Sprintf(`      - uses: actions/checkout@%s`, checkoutSHA), false, ""},
		{"local action", `      - uses: ./local/action@v1`, false, ""},
		{"local action no version", `      - uses: ./local/action`, false, ""},
		{"docker ref", `      - uses: docker://alpine@sha256`, false, ""},
		{"no version", `      - uses: actions/checkout`, false, ""},
		{"single segment", `      - uses: checkout@v7`, false, ""},
		{"mismatched quotes", `      - uses: "actions/checkout@v7`, false, ""},
		{"not a uses line", `        run: echo uses actions/checkout@v7`, false, ""},
		{"name field", `        name: "checkout@v7",`, false, ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			parsed, ok := parseUsesLine(tt.line)
			if ok != tt.ok {
				t.Fatalf("parseUsesLine(%q) ok = %v, want %v", tt.line, ok, tt.ok)
			}
			if ok && parsed.ref.Key() != tt.key {
				t.Errorf("key = %q, want %q", parsed.ref.Key(), tt.key)
			}
		})
	}
}

func TestRewrite(t *testing.T) {
	pins := map[string]string{
		"actions/checkout@v7": checkoutSHA,
		"actions/setup-go@v6": setupGoSHA,
		"octo/repo@v1":        checkoutSHA,
	}
	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			"kyaml quoted with comma",
			`        uses: "actions/checkout@v7",`,
			fmt.Sprintf(`        uses: "actions/checkout@%s", # v7`, checkoutSHA),
		},
		{
			"yaml dash plain",
			`      - uses: actions/setup-go@v6`,
			fmt.Sprintf(`      - uses: actions/setup-go@%s # v6`, setupGoSHA),
		},
		{
			"reusable workflow keeps full path",
			`    uses: octo/repo/.github/workflows/ci.yml@v1`,
			fmt.Sprintf(`    uses: octo/repo/.github/workflows/ci.yml@%s # v1`, checkoutSHA),
		},
		{
			"unknown ref untouched",
			`      - uses: other/action@v2`,
			`      - uses: other/action@v2`,
		},
		{
			"local action untouched",
			`      - uses: ./local/action`,
			`      - uses: ./local/action`,
		},
		{
			"non-uses lines untouched",
			`name: CI`,
			`name: CI`,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := string(Rewrite([]byte(tt.in), pins))
			if got != tt.want {
				t.Errorf("Rewrite(%q)\n got %q\nwant %q", tt.in, got, tt.want)
			}
		})
	}
}

func TestRewritePreservesDocumentStructure(t *testing.T) {
	doc := strings.Join([]string{
		`# Code generated by execuetion; DO NOT EDIT.`,
		`jobs: {`,
		`  build: {`,
		`    steps: [`,
		`      {`,
		`        uses: "actions/checkout@v7",`,
		`      },`,
		`    ],`,
		`  },`,
		`}`,
		``,
	}, "\n")
	got := string(Rewrite([]byte(doc), map[string]string{"actions/checkout@v7": checkoutSHA}))
	want := strings.Replace(doc,
		`uses: "actions/checkout@v7",`,
		fmt.Sprintf(`uses: "actions/checkout@%s", # v7`, checkoutSHA), 1)
	if got != want {
		t.Errorf("Rewrite mangled document\n got:\n%s\nwant:\n%s", got, want)
	}
}

func TestRefsDedup(t *testing.T) {
	doc := strings.Join([]string{
		`      - uses: actions/checkout@v7`,
		`      - uses: actions/setup-go@v6`,
		`      - uses: actions/checkout@v7`,
		`      - uses: actions/checkout@v5`,
	}, "\n")
	refs := Refs([]byte(doc))
	want := []string{"actions/checkout@v7", "actions/setup-go@v6", "actions/checkout@v5"}
	if len(refs) != len(want) {
		t.Fatalf("got %d refs, want %d: %v", len(refs), len(want), refs)
	}
	for i, w := range want {
		if refs[i].Key() != w {
			t.Errorf("refs[%d] = %q, want %q", i, refs[i].Key(), w)
		}
	}
}

// fakeResolver resolves from a fixed map and counts calls.
type fakeResolver struct {
	pins  map[string]string
	calls int
}

func (f *fakeResolver) Resolve(_ context.Context, owner, repo, ref string) (string, error) {
	f.calls++
	sha, ok := f.pins[owner+"/"+repo+"@"+ref]
	if !ok {
		return "", errors.New("not found")
	}
	return sha, nil
}

func testCache(t *testing.T) *Cache {
	t.Helper()
	return Open(filepath.Join(t.TempDir(), "pins.json"))
}

func TestPinnerDedupesAcrossDocs(t *testing.T) {
	resolver := &fakeResolver{pins: map[string]string{
		"actions/checkout@v7": checkoutSHA,
		"actions/setup-go@v6": setupGoSHA,
	}}
	p := &Pinner{Resolver: resolver, Cache: testCache(t)}
	docs := [][]byte{
		[]byte(`      - uses: actions/checkout@v7`),
		[]byte(`      - uses: actions/checkout@v7` + "\n" + `      - uses: actions/setup-go@v6`),
	}
	pinned, err := p.Pin(context.Background(), docs)
	if err != nil {
		t.Fatalf("Pin returned error: %v", err)
	}
	if resolver.calls != 2 {
		t.Errorf("expected 2 resolver calls (one per unique ref), got %d", resolver.calls)
	}
	if !strings.Contains(string(pinned[0]), checkoutSHA) || !strings.Contains(string(pinned[1]), setupGoSHA) {
		t.Errorf("output not pinned:\n%s\n%s", pinned[0], pinned[1])
	}
}

func TestPinnerUsesCache(t *testing.T) {
	cache := testCache(t)
	cache.Put("actions/checkout@v7", checkoutSHA)
	resolver := &fakeResolver{pins: map[string]string{}}
	p := &Pinner{Resolver: resolver, Cache: cache}
	pinned, err := p.Pin(context.Background(), [][]byte{[]byte(`      - uses: actions/checkout@v7`)})
	if err != nil {
		t.Fatalf("Pin returned error: %v", err)
	}
	if resolver.calls != 0 {
		t.Errorf("expected 0 resolver calls on cache hit, got %d", resolver.calls)
	}
	if !strings.Contains(string(pinned[0]), checkoutSHA) {
		t.Errorf("output not pinned from cache: %s", pinned[0])
	}
}

func TestPinnerUpdateIgnoresCache(t *testing.T) {
	cache := testCache(t)
	cache.Put("actions/checkout@v7", strings.Repeat("0", 40))
	resolver := &fakeResolver{pins: map[string]string{"actions/checkout@v7": checkoutSHA}}
	p := &Pinner{Resolver: resolver, Cache: cache, Update: true}
	pinned, err := p.Pin(context.Background(), [][]byte{[]byte(`      - uses: actions/checkout@v7`)})
	if err != nil {
		t.Fatalf("Pin returned error: %v", err)
	}
	if resolver.calls != 1 {
		t.Errorf("expected 1 resolver call with Update, got %d", resolver.calls)
	}
	if !strings.Contains(string(pinned[0]), checkoutSHA) {
		t.Errorf("output not re-pinned: %s", pinned[0])
	}
	if sha, _ := cache.Get("actions/checkout@v7"); sha != checkoutSHA {
		t.Errorf("cache not overwritten: %s", sha)
	}
}

func TestPinnerResolutionFailure(t *testing.T) {
	cachePath := filepath.Join(t.TempDir(), "pins.json")
	resolver := &fakeResolver{pins: map[string]string{"actions/checkout@v7": checkoutSHA}}
	p := &Pinner{Resolver: resolver, Cache: Open(cachePath)}
	docs := [][]byte{[]byte(strings.Join([]string{
		`      - uses: actions/checkout@v7`,
		`      - uses: ghost/missing@v1`,
	}, "\n"))}
	_, err := p.Pin(context.Background(), docs)
	if err == nil {
		t.Fatal("expected error for unresolvable ref")
	}
	if !strings.Contains(err.Error(), "ghost/missing@v1") {
		t.Errorf("error does not name the failing ref: %v", err)
	}
	// The successful resolution must still be persisted.
	if sha, ok := Open(cachePath).Get("actions/checkout@v7"); !ok || sha != checkoutSHA {
		t.Errorf("successful resolution not saved to cache, got %q, %v", sha, ok)
	}
}
